### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by badgerman11** [teemuatlut/MM-thingspeak-module#2]
Hi,
I've problem with installing this module. After installing it I have only blank files. Can you help me with that?

**Comment by teemuatlut** [comment]
Most likely the answer is no, sorry. It's been 3 years now since I worked on this and I haven't had my mirror running for a while. Maybe one day I'll get to updating but it's a very low priority for me atm.

**Comment by badgerman11** [comment]
Ok, i understand. Thanks for reply
